# Generated by Django 3.1.5 on 2021-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='email',
            new_name='from_email',
        ),
        migrations.AddField(
            model_name='email',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='email',
            name='to_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
